// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portal.Data;

#nullable disable

namespace Portal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623124407_AddAlteracaoEscalaAuditoria")]
    partial class AddAlteracaoEscalaAuditoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portal.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("Portal.Models.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CargaHorariaSemanal")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoEscala")
                        .HasColumnType("integer");

                    b.Property<bool?>("TrabalhaDiaParPadrao")
                        .HasColumnType("boolean");

                    b.Property<int?>("TurnoDoze36")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Escala");
                });

            modelBuilder.Entity("Portal.Models.EscalaDetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int>("EscalaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Folga")
                        .HasColumnType("boolean");

                    b.Property<string>("HoraAlmocoFim")
                        .HasColumnType("text");

                    b.Property<string>("HoraAlmocoInicio")
                        .HasColumnType("text");

                    b.Property<string>("HoraFim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HorasPrevistas")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.ToTable("EscalaDetalhe");
                });

            modelBuilder.Entity("Portal.Models.Ferias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Excluded")
                        .HasColumnType("boolean");

                    b.Property<int>("FeriasId")
                        .HasColumnType("integer");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Ferias");
                });

            modelBuilder.Entity("Portal.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CargaHorariaSemanal")
                        .HasColumnType("integer");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDemissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Excluded")
                        .HasColumnType("boolean");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Portal.Models.FuncionarioEscala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EscalaId")
                        .HasColumnType("integer");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<bool?>("TrabalhaDiaPar")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("FuncionarioEscala");
                });

            modelBuilder.Entity("Portal.Models.RegistroPonto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("AtestadoMedico")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EscalaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Excluded")
                        .HasColumnType("boolean");

                    b.Property<bool>("Feriado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ferias")
                        .HasColumnType("boolean");

                    b.Property<bool>("Folga")
                        .HasColumnType("boolean");

                    b.Property<int?>("FuncionarioEscalaId")
                        .HasColumnType("integer");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("HoraAlmocoFim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoraAlmocoInicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoraEntrada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoraSaida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Presenca")
                        .HasColumnType("boolean");

                    b.Property<int>("RegistroPontoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.HasIndex("FuncionarioEscalaId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("RegistroPonto");
                });

            modelBuilder.Entity("Portal.Models.EscalaDetalhe", b =>
                {
                    b.HasOne("Portal.Models.Escala", "Escala")
                        .WithMany("Detalhes")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");
                });

            modelBuilder.Entity("Portal.Models.Ferias", b =>
                {
                    b.HasOne("Portal.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Portal.Models.FuncionarioEscala", b =>
                {
                    b.HasOne("Portal.Models.Escala", "Escala")
                        .WithMany("FuncionarioEscalas")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Portal.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Portal.Models.RegistroPonto", b =>
                {
                    b.HasOne("Portal.Models.Escala", "Escala")
                        .WithMany()
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Portal.Models.FuncionarioEscala", "FuncionarioEscalaVinculo")
                        .WithMany()
                        .HasForeignKey("FuncionarioEscalaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Portal.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId");

                    b.Navigation("Escala");

                    b.Navigation("Funcionario");

                    b.Navigation("FuncionarioEscalaVinculo");
                });

            modelBuilder.Entity("Portal.Models.Escala", b =>
                {
                    b.Navigation("Detalhes");

                    b.Navigation("FuncionarioEscalas");
                });
#pragma warning restore 612, 618
        }
    }
}
